# Generated by Django 6.0.1 on 2026-01-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('politics', 'Politics'), ('education', 'Education'), ('law', 'Law'), ('technology', 'Technology'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
